name: CI
on: { push: { branches: [ main ] }, pull_request: { branches: [ main ] } }
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r reference_impl/requirements.txt
      - name: Lint schema
        run: |
          python - <<'PY'
          import json
          from jsonschema import Draft202012Validator
          s=json.load(open('schema/ohsdm.schema.v1_0.json'))
          Draft202012Validator.check_schema(s)
          print("Schema OK")
          PY
      - name: Tests
        run: |
          source .venv/bin/activate
          pytest -q
